### PR TITLE
Adaptations to nan 2.2.1 

### PR DESCRIPTION
**Pull request by Will-I4M**
The first commit is an error, my apologies. 
Please give me your feedback

### CODE REVIEW

**Comment by Sannis** [comment]
@Will-I4M I've cherry-picked your commit to node-four-update branch and do some code style fixes. It is still broke Travis build, working to fix it.

**Comment by cevek** [comment]
+1

**Comment by Will-I4M** [comment]
Thanks, another version is comming, with better performances on fetch (~3x). I'm just waiting before push because i'm working on a faster method to build the v8 objects (as we can expect in some cases 10x or more). I'm not sure to understand this error with travis. Need help ?

**Comment by cevek** [comment]
Can you also check it with nightly node 6 
https://nodejs.org/download/nightly/

**Comment by Will-I4M** [comment]
I'm quite sure the code need some changes to be v6 ready. For example : https://github.com/nodejs/nan/issues/548 -> the callback APi has changed. I'll check it but not in the next few days ;)

**Comment by cevek** [comment]
@Will-I4M  How can I install this module from your PR?

**Comment by Will-I4M** [comment]
Sorry for this late answer ... You can install it from my fork, if you need it now. 
I'll try to push the next release this we, or next week.

**Comment by cevek** [comment]
Any updates?

**Comment by Sannis** [comment]
I've continue fixing this in node-nan-update branch, feel free to make further pull request on top of it.

**Pull request closed without merging**
